apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudcampus-backend-db
  namespace: cloudcampus
  annotations:
    argocd.argoproj.io/sync-wave: "0"

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: cloudcampus-backend-db
    creationPolicy: Owner

  data:
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: rds!db-14034b3c-8057-43e5-a32d-4a9212cd290a
        property: username

    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: rds!db-14034b3c-8057-43e5-a32d-4a9212cd290a
        property: password
