replicaCount: 2

image:
  repository: 541227054167.dkr.ecr.us-west-2.amazonaws.com/dev-frontend
  tag: "14-2ab8645"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

containerPort: 80

health:
  path: /

ingress:
  enabled: true
  scheme: internet-facing
  targetType: ip
  healthcheckPath: /
  host: mybanking.shop
  certificateArn: "arn:aws:acm:us-west-2:541227054167:certificate/34e10bd8-78d6-4412-a30a-52a9ebc5b46e"
